title: My personal Blog
author: Vivianas14
email: vsoriano@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I’m Viviana and I’m glad you are here. I plan to talk about my process of learning web programming and how happy I am.
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: bumy7 # DO NOT include the @ character, or else the build will fail!
github_username:  Vivianas14 # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
theme: minima
